#LobbyManager Default Configuration

#Language of serveur [available : en, fr].
lang: en

#If enable players can't have any damage.
noDamage:
  enable: true

#If true players can't drop item.
antidrop:
  enable: true

#If true players will not fall below the given value.
noFall:
  enable: true
  level: 40

join:
  #If enable players join the game in the given gamemode.
  gamemode:
    enable: false
    gamemode: 2
  #If enable players who join the game receive title and subtitle.
  title:
    enable: true
    title: Welcome on this server !
    subtitle: This server use LobbyManager !

#If enable was true, inventory was send to players
inventory:
  control:
    enable: true
  give:
    enable: true
    0:
      item:
        ID: PAPER
        name: "server's menu"
        enchant:
          name: LURE
          level: 0
      action: say LobbyManager work good !
