main: fr.pelt10.lobbymanager.LobbyManager
name: LobbyManager
version: 1.1
author: Pelt10
commands:
    spawn:
        usage: /<command>
        description: Go to spawnpoint
        aliases: []
        permission: lobbymanager.spawn
    setspawn:
        usage: /<command>
        description: Set spawnpoint
        aliases: []
        permission: lobbymanager.setspawn
    reloadinventory:
        usage: /<command>
        description: Reload inventory !
        aliases: []
        permission: lobbymanager.reloadinventory
permissions:
    lobbymanager.gmBypass:
        description: Allow to bypass the gamemode set on join.
        default: op
    lobbymanager.useInventory:
        description: Allow to use Inventory when Inventory.control.enable = true.
        default: op
    lobbymanager.reloadinventory:
        description: Reload inventory of player when he had modification in configuration file.
        default: op
    lobbymanager.spawn:
        description: Teleport to spawn location.
        default: not op
    lobbymanager.setspawn:
        description: Set spawn location.
        default: op
